### ISSUE TITLE
Very high cpu usage (patch included)

### ISSUE THREAD

**Issue by cberner** [cvg/px-ros-pkg#1]
When running the px4flow_node on my Pandaboard (Cortex A9 1.2GHz), I see ~90% cpu usage, and an update rate of only ~45Hz on px4flow/opt_flow. On my laptop, which has a Core2 processor, I see ~40% cpu usage, and ~95Hz update rate.

This appears to be due to inefficient reading of bytes from the serial connection, I'm including a patch, which reduces the cpu usage to ~4% on my Pandaboard with an update rate of ~95Hz

**Comment by LorenzMeier** [comment]
Fixed by cberner.
