### ISSUE TITLE
compile error (by groovy)

### ISSUE THREAD

**Issue by stmoon** [cvg/px-ros-pkg#10]
Hi,... 

I tried to compile other board (version groovy is used).
Unfortunately, there are some errors like below.
However I don't know how to solve this problem..

Thanks in advance.

---

Could not find a configuration file for package cmake_modules.

  Set cmake_modules_DIR to the directory containing a CMake configuration
  file for cmake_modules.  The file will have one of the following names:

```
cmake_modulesConfig.cmake
cmake_modules-config.cmake
```

Call Stack (most recent call first):
  px4flow/drivers/mavlink_serial_client/CMakeLists.txt:4 (find_package)

**Comment by hengli** [comment]
You need to install the package ros-groovy-cmake-modules.

**Comment by stmoon** [comment]
Wow too fast...:-)

Thanks...

**Comment by stmoon** [comment]
it works... Thankss...
