### ISSUE TITLE
cmake_modules needs to be removed from CMakeLists.txt and package.xml for hydro

### ISSUE THREAD

**Issue by dani-carbonell** [cvg/px-ros-pkg#7]
An error occurs when compiling in hydro. I think you should release a new branch, put a conditional inside the files or indicate to remove this line for hydro users.

**Comment by hengli** [comment]
For ROS Hydro, you can install the ros-hydro-cmake-modules package if you are using Ubuntu. Then, the code should be able to compile in Hydro.
