### ISSUE TITLE
/px4flow/camera_image is being published without output

### ISSUE THREAD

**Issue by dani-carbonell** [cvg/px-ros-pkg#8]
I am using hydro and ubuntu 12.04. I can rostopic echo successfully /px4flow/opt_flow
but in  /px4flow/camera_image\* topic nothing seems to be published.
Could you help me?

**Comment by scott-eddy** [comment]
Dani,
We are also using hydro and ubuntu 12.04.  Our PX4flow has exhibits the same behavior yours was as we can echo /px4flow/opt_flow but the /px4flow/camera_image can not be viewed.

When running:
'rosrun image_view image_view image:=/px4flow/camera_image,' 

It can be seen in rqt_graph that the topic /px4flow/camera_image is being published and the image_view node is subscribed to it, but there is no data.

Have you had any success in getting the camera_image?

**Comment by vliedel** [comment]
Same problem here on hydro and indigo

**Comment by dani-carbonell** [comment]
No progress. I left it by the moment.

**Comment by hengli** [comment]
The most probable reason is that the MAVLINK files being used by px-ros-pkg and PX4Flow are of different versions. If one of you has time, you could update the MAVLINK files in px-ros-pkg to match those used by PX4Flow.

**Comment by vliedel** [comment]
Any suggestions how to do that?

**Comment by Fromandto** [comment]
https://groups.google.com/forum/#!topic/px4users/UxvxMb1UpL0
The end of this post says 

Problem solved by updating the camera firmware ;)

So, topic closed!

Is this useful ? I'm still trying to install QGroundControl and update camera firmware

**Comment by scott-eddy** [comment]
Installing QGroundControl and updating the camera firmware fixes the problem.

Also, if the image you see on ros is blurry try focusing the camera manually as described in this post:  https://groups.google.com/forum/#!topic/px4users/IsvLaI2kQEg

Thanks for finding the solution Formandto

**Comment by Fromandto** [comment]
I got the stream as well, although the resolution is very low(lower than 752 \* 480 or 480 \* 320).

**Comment by migferram** [comment]
Hello everybody. Fromandto, I have same problem, the resolution is very low. Did you solve that?
Thank you
