### ISSUE TITLE
/px4flow/opt_flow error

### ISSUE THREAD

**Issue by stmoon** [cvg/px-ros-pkg#9]
Hi,,

when run the command "/px4flow/opt_flow", the error happen like below....

ERROR: Cannot load message class for [px_comm/OpticalFlow]. Are your messages built?

**Comment by hengli** [comment]
If the command "rosmsg show px_comm/OpticalFlow" does not work, check that the environment variable ROS_PACKAGE_PATH contains the path to the px_comm package. (Or perhaps you forgot to source ~/catkin_ws/devel/setup.bash)

**Comment by stmoon** [comment]
Thanks it works!!!

However I don't know why it works.. (Actually, I did setup.bash)

Anyway Thanks

2014-07-23 18:54 GMT+09:00 hengli notifications@github.com:
